name: AcevedoTravels
favicon: null
layout_spectrum: 0.6693097
typography_spectrum: 0.6291329
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2e4d11'
    - '#6a9836'
    - '#c4c5c7'
    - '#0b0f07'
  brandStrength: 0.9676882
  lightness: 0
  saturation: 0.5214823
  rhythmicContrast: 0.01557462
purpose: []
