layout_spectrum: 0.420664
typography_spectrum: 0.6291329
color:
  saturation: 0.8186562
  lightness: 0.2911029
  brandStrength: 0.9676882
  rhythmicContrast: 0.2606879
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: AcevedoTravels
