collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6291329
color:
  saturation: 0.5214823
  brandStrength: 0.9676882
  rhythmicContrast: 0.01557462
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0
layout_spectrum: 0.3362873
name: AcevedoTravels
